spring:
  application:
    name: gateway
  config:
    import:
      - optional:file:.env
      - optional:file:../.env
  data:
    redis:
      host: ${REDIS_HOST:?REDIS_HOST is required}
      port: ${REDIS_PORT:?REDIS_PORT is required}
      password: ${REDIS_PASSWORD:?REDIS_PASSWORD is required}
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/auth/**

server:
  port: ${GATEWAY_SERVICE_PORT:?GATEWAY_SERVICE_PORT is required}
